Repository replicatedhq/kots-helm, pull requests merged in 2024-01, with the labels that each got.

#32 feat: add kurl proxy resources to AdminConsole helm chart
  .helmignore
  scripts/build-local.sh
  scripts/build-ttl.sh
  templates/NOTES.txt
  templates/kotsadm-service.yaml
  templates/kurl-proxy-deployment.yaml
  templates/kurl-proxy-rbac.yaml
  templates/kurl-proxy-service.yaml
  values.yaml.tmpl
Labels: type::feature

#33 bug: chart cannot be updated due to wanting to change immutable fields.
  templates/_helpers.tpl
  templates/minio-statefulset.yaml
  templates/rqlite-statefulset.yaml
Labels: type::bug, bug::normal

#34 add 'http' label to kurl-proxy-kotsadm service port
  templates/kurl-proxy-service.yaml
Labels: type::chore
