Repository replicatedhq/kots-helm, pull requests merged in 2024-09, with the labels that each got.

#53 Allow running on arm64 nodes
  values.yaml.tmpl
Labels: type::feature

#55 fix(proxy): use fqdn for kotsadm-rqlite address
  templates/secret-rqlite.yaml
Labels: type::bug, bug::normal

#56 fix: use fqdn for kotsadm-minio for proxy support
  templates/migrate-s3-hook.yaml
Labels: type::bug, bug::normal

#57 always create cas configmap and mount it in kotsadm pod
  templates/configmap-extra-cas.yaml
  templates/kotsadm-deployment.yaml
Labels: type::feature

#59 do not include CA configmap in helm chart, use it by reference
  templates/configmap-private-cas.yaml
  templates/kotsadm-deployment.yaml
  values.yaml.tmpl
Labels: type::chore

#60 pass in CA cert configmap name as env var and quote things
  templates/kotsadm-deployment.yaml
Labels: type::chore

#61 bug: fix config map entry on deployment
  templates/kotsadm-deployment.yaml
Labels: type::bug, bug::normal

#62 add embedded cluster ID to kurl-proxy
  templates/kurl-proxy-deployment.yaml
Labels: type::chore
