Repository replicatedhq/kots-helm, pull requests merged in 2025-04, with the labels that each got.

#74 fix: kotsadm deployment strategy recreate
  templates/kotsadm-deployment.yaml
Labels: bug, type::bug, bug::normal

#75 chore(ci): update github actions runner to ubuntu-24.04
  .github/workflows/publish-production.yaml
  .github/workflows/publish-staging.yaml
Labels: type::chore

#76 wait for rqlite to be synced not just ready
  templates/rqlite-statefulset.yaml
Labels: type::bug, bug::normal

#78 rename isMultiNodeDisabled to isMultiNodeEnabled
  templates/kurl-proxy-deployment.yaml
  values.yaml.tmpl
Labels: type::feature

#79 Add support for EC tags
  .github/workflows/publish-ec.yaml
  .github/workflows/publish-staging.yaml
Labels: type::feature

#80 Mount the EC data directory into the kots deployment
  templates/kotsadm-deployment.yaml
  values.yaml.tmpl
Labels: type::feature

#81 Mount the k0s data directory into the kots deployment
  templates/kotsadm-deployment.yaml
  values.yaml.tmpl
Labels: type::feature
